name: CI

on: 
  - pull_request
  - push

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: make install
      run: make install

    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.4'
          coverage: xdebug
            
    - name: Install dependencies with composer
      run: composer update --no-ansi --no-interaction --no-progress

    - name: make lint
      run: make lint
      
    - name: make test
      run: make test-coverage
          
    - name: Run tests with phpunit/phpunit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}