name: CI

on: 
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate composer.json and composer.lock
      run: make validate
    
    - name: make install
      run: make install
    
    - name: make lint
      run: make lint
      
    - name: make test
      run: make test-coverage

    - name: Setup PHP with Xdebug
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.1'
          coverage: xdebug
            
    - name: Install dependencies with composer
      run: composer update --no-ansi --no-interaction --no-progress
          
    - name: Run tests with phpunit/phpunit
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
      
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=Gubanov07_php-project-48
          -Dsonar.php.coverage.reportPaths=coverage.xml
          -Dsonar.coverage.exclusions=**/vendor/**,**/tests/**
          -Dsonar.sources=src
          -Dsonar.tests=tests