name: CI

on: 
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate composer.json and composer.lock
      run: make validate
    
    - name: make install
      run: make install
    
    - name: make lint
      run: make lint
      
    - name: make test
      run: make test-coverage
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
